/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Reportes.Reporte;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.util.Date;
import static persistenciaDatos.PersistenciaDeDatos.sinMora;

/**
 *
 * @author DAVID
 */
public class Fondos extends javax.swing.JFrame {

    private VentanaPrincipal frame;
    private Reporte reporte;

    public Fondos(VentanaPrincipal frame, Reporte reporte) {
        initComponents();
        this.frame = frame;
        this.reporte = reporte;
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                abrirSegundoJFrame();
            }
        });
    }
    private void abrirSegundoJFrame() {
        frame.setVisible(true);
    }

    public void mostrarFondos(Date dateUno, Date dateDos) throws ParseException {
        if (dateUno != null && dateDos != null) {
            this.reporte.interMoras(dateUno, dateDos);
            this.reporte.interSinMoras(dateUno, dateDos);
            this.reporte.calcularFondos(1, jTextPane1);
            int mora = this.reporte.getFondosConMora();
            int noMora = this.reporte.getFondosSinMora();
            int total = mora+noMora;
            this.TotalI6.setText("" + total);
            this.morasI6.setText("" + mora);
            this.prestamosI6.setText("" + noMora);
        } else {
            this.reporte.calcularFondos(2, jTextPane1);
            int mora = this.reporte.getFondosConMora();
            int noMora = this.reporte.getFondosSinMora();
            int total = mora+noMora;
            this.TotalI6.setText("" + total);
            this.morasI6.setText("" + mora);
            this.prestamosI6.setText("" + noMora);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        mora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        prestamosI6 = new javax.swing.JLabel();
        TotalI6 = new javax.swing.JLabel();
        morasI6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setResizable(false);

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mora.setText("Ingresos por Moras:");
        jPanel8.add(mora, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 124, -1));

        jLabel1.setText("Ingresos por prestamos:");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 138, -1));

        jLabel2.setText("Total:");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 37, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        prestamosI6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TotalI6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        morasI6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(morasI6, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(prestamosI6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalI6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(morasI6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prestamosI6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalI6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel3.setText("Prestamos:");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 67, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        jTextPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPane1.setEnabled(false);
        jScrollPane1.setViewportView(jTextPane1);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 442, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalI;
    private javax.swing.JLabel TotalI1;
    private javax.swing.JLabel TotalI2;
    private javax.swing.JLabel TotalI3;
    private javax.swing.JLabel TotalI4;
    private javax.swing.JLabel TotalI5;
    private javax.swing.JLabel TotalI6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel mora;
    private javax.swing.JLabel morasI;
    private javax.swing.JLabel morasI1;
    private javax.swing.JLabel morasI2;
    private javax.swing.JLabel morasI3;
    private javax.swing.JLabel morasI4;
    private javax.swing.JLabel morasI5;
    private javax.swing.JLabel morasI6;
    private javax.swing.JLabel prestamosI;
    private javax.swing.JLabel prestamosI1;
    private javax.swing.JLabel prestamosI2;
    private javax.swing.JLabel prestamosI3;
    private javax.swing.JLabel prestamosI4;
    private javax.swing.JLabel prestamosI5;
    private javax.swing.JLabel prestamosI6;
    // End of variables declaration//GEN-END:variables
}
