/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import DataBase.SaveAndReaderBinary;
import cargaDeDatos.Libro;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import persistenciaDatos.ControlDatosLibros;
import persistenciaDatos.PersistenciaDeDatos;

/**
 *
 * @author Kenny Salazar
 */
public class NuevoLibro extends javax.swing.JFrame {

    /**
     * Creates new form NuevosLibros
     */
    // --------------EDITAR LIBRO---------------------
    boolean isEdit;
    Libro libro;
    JTable tabla;
    SaveAndReaderBinary LyE = new SaveAndReaderBinary();

    NuevoLibro(boolean isEdit, Libro libro, JTable tabla) {
        this.isEdit = isEdit;
        this.libro = libro;
        this.tabla = tabla;
        initComponents();
        IniciarCombosFecha();
        cantidadCopias();

        if (isEdit) {
            this.codigoTextField.setText(libro.getCodigo());
            this.codigoTextField.setEditable(false);
            this.autorTextField.setText(libro.getAutor());
            this.tituloTextField.setText(libro.getTitulo());
            this.comboCopias.setSelectedIndex((libro.getCantidad()));
            this.editorialTextField.setText(libro.getEditorial());
            //falta fecha y editorial
            System.out.println(libro.getFechaDePublicacion());
            try {
                String fechaPublicación[] = libro.getFechaDePublicacion().split("-");
                this.comboAnio.setSelectedItem(fechaPublicación[0]);
                this.comboMes.setSelectedItem(fechaPublicación[1]);
                this.comboDia.setSelectedItem(fechaPublicación[2]);
            } catch (Exception e) {
                System.out.println("No trae fecha");
            }

        }
    }

    public NuevoLibro() {
        initComponents();
        cantidadCopias();
        IniciarCombosFecha();
    }

    public void cantidadCopias() {
        for (int i = 0; i < 100; i++) {
            this.comboCopias.addItem("" + i);

        }
    }

    public void IniciarCombosFecha() {
        for (int i = 1900; i < 2024; i++) {
            this.comboAnio.addItem("" + i);
        }
        for (int i = 1; i <= 12; i++) {
            this.comboMes.addItem("" + i);
        }
        for (int i = 1; i <= 31; i++) {
            this.comboDia.addItem("" + i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigoTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tituloTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboAnio = new javax.swing.JComboBox<>();
        comboMes = new javax.swing.JComboBox<>();
        comboDia = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboCopias = new javax.swing.JComboBox<>();
        BtGuadarNuevoLibro = new javax.swing.JButton();
        autorTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        editorialTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese los datos del nuevo libro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 6, -1, -1));
        jPanel1.add(codigoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 50, 287, -1));

        jLabel2.setText("Código:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 28, -1, -1));

        jLabel3.setText("Autor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 88, -1, -1));
        jPanel1.add(tituloTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 174, 287, -1));

        jLabel4.setText("Cantidad de copias");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 212, -1, -1));

        jLabel5.setText("Fecha de publicación");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 278, -1, -1));

        comboAnio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAnioActionPerformed(evt);
            }
        });
        jPanel1.add(comboAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 328, -1, -1));

        comboMes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesActionPerformed(evt);
            }
        });
        jPanel1.add(comboMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 328, -1, -1));

        comboDia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(comboDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 328, -1, -1));

        jLabel6.setText("Año");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 306, -1, -1));

        jLabel7.setText("Mes");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 306, -1, -1));

        jLabel8.setText("Dia");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 306, -1, -1));

        comboCopias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(comboCopias, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 234, 287, -1));

        BtGuadarNuevoLibro.setText("Guardar");
        BtGuadarNuevoLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtGuadarNuevoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuadarNuevoLibroActionPerformed(evt);
            }
        });
        jPanel1.add(BtGuadarNuevoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 450, 148, -1));
        jPanel1.add(autorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 110, 287, -1));

        jLabel9.setText("Titulo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 154, -1, -1));
        jPanel1.add(editorialTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 406, 330, -1));

        jLabel10.setText("Editorial");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 378, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAnioActionPerformed

    private void comboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMesActionPerformed

    private void BtGuadarNuevoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuadarNuevoLibroActionPerformed
        // TODO add your handling code here:
        ControlDatosLibros controlLibro = new ControlDatosLibros();
        JFrame jFrame = new JFrame();
        if (!isEdit) {
            if (!codigoTextField.getText().equalsIgnoreCase("")) {
                
                    if (!autorTextField.getText().equalsIgnoreCase("") && !tituloTextField.getText().equalsIgnoreCase("")) {
                        String codigo = codigoTextField.getText();
                        String titulo = tituloTextField.getText();
                        String editorial = editorialTextField.getText();
                        String fechaPublicacion = (String) comboAnio.getSelectedItem() + "-" + comboMes.getSelectedItem() + "-" + comboDia.getSelectedItem();
                        controlLibro.guardarNuevoLibro(tituloTextField.getText(), autorTextField.getText(), codigoTextField.getText(), String.valueOf(comboCopias.getSelectedIndex()), fechaPublicacion, editorialTextField.getText(), tabla);
                        JOptionPane.showMessageDialog(jFrame, "Se ha guardado el nuevo Libro");

                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(jFrame, "Debes rellenar todos los campos");
                    }
                
            } else{
                JOptionPane.showMessageDialog(jFrame, "El codigo no debe ser nulo");
            }
            
        } else {
                for (int i = 0; i < PersistenciaDeDatos.biblio.size(); i++) {
                    if (PersistenciaDeDatos.biblio.get(i).getCodigo().equals(codigoTextField.getText())) {
                        PersistenciaDeDatos.biblio.get(i).setAutor(autorTextField.getText());
                        PersistenciaDeDatos.biblio.get(i).setTitulo(tituloTextField.getText());
                        PersistenciaDeDatos.biblio.get(i).setCantidad((comboCopias.getSelectedIndex()));
                        String fechaPublicacion = (String) comboAnio.getSelectedItem() + "-" + comboMes.getSelectedItem() + "-" + comboDia.getSelectedItem();
                        PersistenciaDeDatos.biblio.get(i).setFechaDePublicacion(fechaPublicacion);
                        PersistenciaDeDatos.biblio.get(i).setEditorial(editorialTextField.getText());
                        JOptionPane.showMessageDialog(jFrame, "Se ha modificado el libro: " + libro.getCodigo());
                        controlLibro.llenarTablaLibros(tabla);
                        LyE.guardarArchivoBinario();
                        i = PersistenciaDeDatos.biblio.size();
                    }

                }
                this.dispose();
            }

    }//GEN-LAST:event_BtGuadarNuevoLibroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtGuadarNuevoLibro;
    private javax.swing.JTextField autorTextField;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JComboBox<String> comboAnio;
    private javax.swing.JComboBox<String> comboCopias;
    private javax.swing.JComboBox<String> comboDia;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JTextField editorialTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tituloTextField;
    // End of variables declaration//GEN-END:variables
}
