/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import DataBase.SaveAndReaderBinary;
import Reportes.Reporte;
import cargaDeDatos.Estudiante;
import cargaDeDatos.Libro;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import persistenciaDatos.ControlDatosEstudiante;
import persistenciaDatos.ControlDatosLibros;
import persistenciaDatos.ControlDePrestamos;
import persistenciaDatos.PersistenciaDeDatos;
import vista.regresoDeLibro;

/**
 *
 * @author Kenny
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    Estudiante estudianteEdit;
    Libro libroEdit;
    private Reporte reporte;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        reporte = new Reporte();
        initComponents();
        ControlDatosEstudiante controlDatosEstudiante = new ControlDatosEstudiante();
        ControlDatosLibros controlDatosLibros = new ControlDatosLibros();
        ControlDePrestamos controlPrestamos = new ControlDePrestamos();
        this.editarEstudianteBt.setEnabled(false);
        this.eliminarEstudianteBt.setEnabled(false);
        this.editarLibro.setEnabled(false);
        this.eliminarLibro.setEnabled(false);
        this.eliminarPrestamosBt.setEnabled(false);
        controlDatosEstudiante.llenarTablaEstudiantes(this.tablaStudents);
        controlDatosLibros.llenarTablaLibros(this.tablaLibros);
        controlPrestamos.llenarTablaPrestamos(tablaPrestamos);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        nuevoEstudiante = new javax.swing.JButton();
        editarEstudianteBt = new javax.swing.JButton();
        eliminarEstudianteBt = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        labelBusqueda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaStudents = new javax.swing.JTable();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        nuevoLibroButton = new javax.swing.JButton();
        editarLibro = new javax.swing.JButton();
        eliminarLibro = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        labelBusquedaLibro = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        nuevoPrestamosBt = new javax.swing.JButton();
        eliminarPrestamosBt = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        labelBusquedaPestamo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPrestamos = new javax.swing.JTable();
        busquedaComboBox = new javax.swing.JComboBox<>();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        textPaneCarnet = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        historial = new javax.swing.JButton();
        activos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        nuevoEstudiante.setText("Nuevo");
        nuevoEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoEstudianteActionPerformed(evt);
            }
        });

        editarEstudianteBt.setText("Editar");
        editarEstudianteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEstudianteBtActionPerformed(evt);
            }
        });

        eliminarEstudianteBt.setText("Eliminar");
        eliminarEstudianteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEstudianteBtActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        labelBusqueda.setText("Busqueda");

        tablaStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "1212", "1212", "1212"},
                {"2", "232", "2323", "2323"},
                {"23", "2323", "343", "dews"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Carnet", "Nombre", "Carrera", "Fecha de Nacimiento"
            }
        ));
        tablaStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaStudentsMouseClicked(evt);
            }
        });
        tablaStudents.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaStudentsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaStudents);

        jDesktopPane1.setLayer(nuevoEstudiante, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(editarEstudianteBt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(eliminarEstudianteBt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labelBusqueda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(nuevoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(editarEstudianteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(eliminarEstudianteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoEstudiante)
                    .addComponent(editarEstudianteBt)
                    .addComponent(eliminarEstudianteBt))
                .addGap(28, 28, 28)
                .addComponent(labelBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estudiantes", jDesktopPane1);

        nuevoLibroButton.setText("Nuevo");
        nuevoLibroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoLibroButtonActionPerformed(evt);
            }
        });

        editarLibro.setText("Editar");
        editarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarLibroActionPerformed(evt);
            }
        });

        eliminarLibro.setText("Eliminar");
        eliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarLibroActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        labelBusquedaLibro.setText("Busqueda");

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "1212", "1212", "1212", null, null},
                {"2", "232", "2323", "2323", null, null},
                {"23", "2323", "343", "dews", null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Título", "Autor", "Código", "Cantidad de Copias", "Fercha de Publicación", "Editorial"
            }
        ));
        tablaLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaLibrosMouseClicked(evt);
            }
        });
        tablaLibros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaLibrosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablaLibros);
        if (tablaLibros.getColumnModel().getColumnCount() > 0) {
            tablaLibros.getColumnModel().getColumn(3).setHeaderValue("Cantidad de Copias");
            tablaLibros.getColumnModel().getColumn(4).setHeaderValue("Fercha de Publicación");
            tablaLibros.getColumnModel().getColumn(5).setHeaderValue("Editorial");
        }

        jDesktopPane5.setLayer(nuevoLibroButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(editarLibro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(eliminarLibro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(labelBusquedaLibro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane5Layout.createSequentialGroup()
                        .addComponent(nuevoLibroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(editarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(eliminarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelBusquedaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoLibroButton)
                    .addComponent(editarLibro)
                    .addComponent(eliminarLibro))
                .addGap(28, 28, 28)
                .addComponent(labelBusquedaLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jDesktopPane2.setLayer(jDesktopPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                    .addContainerGap(10, Short.MAX_VALUE)
                    .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Libros", jDesktopPane2);

        nuevoPrestamosBt.setText("Nuevo");
        nuevoPrestamosBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoPrestamosBtActionPerformed(evt);
            }
        });

        eliminarPrestamosBt.setText("Regreso de Libro");
        eliminarPrestamosBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarPrestamosBtMouseClicked(evt);
            }
        });
        eliminarPrestamosBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPrestamosBtActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        labelBusquedaPestamo.setText("Busqueda");

        tablaPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "1212", "1212"},
                {"2", "232", "2323"},
                {"23", "2323", "343"},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CódigoLibro", "Carnet", "Fecha"
            }
        ));
        tablaPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPrestamosMouseClicked(evt);
            }
        });
        tablaPrestamos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaPrestamosKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tablaPrestamos);

        jDesktopPane6.setLayer(nuevoPrestamosBt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(eliminarPrestamosBt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(labelBusquedaPestamo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane6Layout = new javax.swing.GroupLayout(jDesktopPane6);
        jDesktopPane6.setLayout(jDesktopPane6Layout);
        jDesktopPane6Layout.setHorizontalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane6Layout.createSequentialGroup()
                        .addComponent(nuevoPrestamosBt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(295, 295, 295)
                        .addComponent(eliminarPrestamosBt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelBusquedaPestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jDesktopPane6Layout.setVerticalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoPrestamosBt)
                    .addComponent(eliminarPrestamosBt))
                .addGap(28, 28, 28)
                .addComponent(labelBusquedaPestamo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        busquedaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Busqueda", "Todos Los Registros", "Codigo del Libro", "Carnet", "Fecha" }));
        busquedaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaComboBoxActionPerformed(evt);
            }
        });

        jDesktopPane4.setLayer(jDesktopPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(busquedaComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane4Layout.createSequentialGroup()
                .addContainerGap(629, Short.MAX_VALUE)
                .addComponent(busquedaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane4Layout.createSequentialGroup()
                    .addContainerGap(12, Short.MAX_VALUE)
                    .addComponent(jDesktopPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(busquedaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(455, Short.MAX_VALUE))
            .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Prestamos", jDesktopPane4);

        jToggleButton1.setText("listado de entregas de hoy");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(textPaneCarnet);

        jLabel1.setText("Reportes por estudiante");

        historial.setText("Historial de prestamos");
        historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialActionPerformed(evt);
            }
        });

        activos.setText("prestamos activos");
        activos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activosActionPerformed(evt);
            }
        });

        jLabel2.setText("buscar carnet :");

        jDesktopPane3.setLayer(jToggleButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(historial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(activos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(historial)
                        .addGap(26, 26, 26)
                        .addComponent(activos)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jToggleButton1)
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(historial)
                        .addComponent(activos))
                    .addComponent(jLabel2))
                .addContainerGap(420, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reportes", jDesktopPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void nuevoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoEstudianteActionPerformed
        // TODO add your handling code here:
        ventanaNuevoEst();
    }//GEN-LAST:event_nuevoEstudianteActionPerformed

    private void tablaStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaStudentsMouseClicked
        // TODO add your handling code here:
        this.editarEstudianteBt.setEnabled(true);
        this.eliminarEstudianteBt.setEnabled(true);
        int fila = tablaStudents.getSelectedRow();
        String carnet = (String) tablaStudents.getValueAt(fila, 1);
        labelBusqueda.setText("" + carnet);
        for (int i = 0; i < PersistenciaDeDatos.estudiantes.size(); i++) {
            if (PersistenciaDeDatos.estudiantes.get(i).getCarnet() == (Integer.parseInt(carnet))) {
                this.estudianteEdit = PersistenciaDeDatos.estudiantes.get(i);
                i = PersistenciaDeDatos.estudiantes.size();

            }
        }

    }//GEN-LAST:event_tablaStudentsMouseClicked

    private void tablaStudentsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaStudentsKeyPressed

    }//GEN-LAST:event_tablaStudentsKeyPressed

    private void nuevoLibroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoLibroButtonActionPerformed
        // TODO add your handling code here:
        ventanaNuevoLibro();
    }//GEN-LAST:event_nuevoLibroButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void tablaLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaLibrosMouseClicked
        // TODO add your handling code here:
        this.editarLibro.setEnabled(true);
        this.eliminarLibro.setEnabled(true);
        int fila = tablaLibros.getSelectedRow();
        String codigo = (String) tablaLibros.getValueAt(fila, 3);
        labelBusquedaLibro.setText("" + codigo);
        //---------------------LIBRO EDITAR--------------------//
        for (int i = 0; i < PersistenciaDeDatos.biblio.size(); i++) {
            if (PersistenciaDeDatos.biblio.get(i).getCodigo().equals(codigo)) {
                this.libroEdit = PersistenciaDeDatos.biblio.get(i);
                i = PersistenciaDeDatos.biblio.size();

            }
        }
    }//GEN-LAST:event_tablaLibrosMouseClicked

    private void tablaLibrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaLibrosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaLibrosKeyPressed

    private void nuevoPrestamosBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoPrestamosBtActionPerformed
        // TODO add your handling code here:
        ventanaNuevoPestamo();


    }//GEN-LAST:event_nuevoPrestamosBtActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void eliminarPrestamosBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarPrestamosBtMouseClicked
    }//GEN-LAST:event_eliminarPrestamosBtMouseClicked

    private void editarEstudianteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEstudianteBtActionPerformed
        // TODO add your handling code here:
        NuevoEstudiante editarEst = new NuevoEstudiante(true, estudianteEdit, this.tablaStudents);
        editarEst.setVisible(true);
        editarEst.setResizable(true);
        editarEst.setLocationRelativeTo(null);
    }//GEN-LAST:event_editarEstudianteBtActionPerformed

    private void eliminarEstudianteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEstudianteBtActionPerformed
        // TODO add your handling code here:
        JFrame jFrame = new JFrame();
        int result = JOptionPane.showConfirmDialog(jFrame, "Desea eliminar el estudiante: " + estudianteEdit.getCarnet());
        if (result == 0) {
            for (int i = 0; i < PersistenciaDeDatos.estudiantes.size(); i++) {
                if (PersistenciaDeDatos.estudiantes.get(i).getCarnet() == (estudianteEdit.getCarnet())) {
                    PersistenciaDeDatos.estudiantes.remove(i);
                    i = PersistenciaDeDatos.estudiantes.size();
                    ControlDatosEstudiante control = new ControlDatosEstudiante();
                    control.llenarTablaEstudiantes(this.tablaStudents);
                    SaveAndReaderBinary s = new SaveAndReaderBinary();
                    s.guardarArchivoBinario();
                }

            }
        } else if (result == 1) {

        } else {

        }
    }//GEN-LAST:event_eliminarEstudianteBtActionPerformed

    private void editarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarLibroActionPerformed
        // TODO add your handling code here:
        NuevoLibro editarLibro = new NuevoLibro(true, libroEdit, this.tablaLibros);
        editarLibro.setVisible(true);
        editarLibro.setResizable(true);
        editarLibro.setLocationRelativeTo(null);
    }//GEN-LAST:event_editarLibroActionPerformed

    private void eliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarLibroActionPerformed
        // TODO add your handling code here:
        JFrame jFrame = new JFrame();
        int result = JOptionPane.showConfirmDialog(jFrame, "Desea eliminar el libro: " + libroEdit.getCodigo());
        if (result == 0) {
            for (int i = 0; i < PersistenciaDeDatos.biblio.size(); i++) {
                if (PersistenciaDeDatos.biblio.get(i).getCodigo().equals(libroEdit.getCodigo())) {
                    PersistenciaDeDatos.biblio.remove(i);
                    i = PersistenciaDeDatos.biblio.size();
                    ControlDatosLibros controlDatosLibro = new ControlDatosLibros();
                    controlDatosLibro.llenarTablaLibros(this.tablaLibros);
                    SaveAndReaderBinary s = new SaveAndReaderBinary();
                    s.guardarArchivoBinario();
                }

            }
        } else if (result == 1) {

        } else {

        }
    }//GEN-LAST:event_eliminarLibroActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

       this.reporte.recorrerPrestamos();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialActionPerformed
        int carnet = Integer.parseInt(this.textPaneCarnet.getText());
        this.reporte.historialEstudiante(carnet);
    }//GEN-LAST:event_historialActionPerformed

    private void activosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activosActionPerformed
        int carnet = Integer.parseInt(this.textPaneCarnet.getText());
        this.reporte.prestamosEstudiante(carnet);
    }//GEN-LAST:event_activosActionPerformed

    private void eliminarPrestamosBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPrestamosBtActionPerformed
        //ventana recibir el libro

        libroRegresado();
        actualizarTabla();

    }//GEN-LAST:event_eliminarPrestamosBtActionPerformed

    private void tablaPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPrestamosMouseClicked
        // TODO add your handling code here:
        this.eliminarPrestamosBt.setEnabled(true);
        int fila = tablaPrestamos.getSelectedRow();
//        String codigo = (String) tablaPrestamos.getValueAt(fila, 0).toString();
//        String carnet = (String) tablaPrestamos.getValueAt(fila, 1).toString();
//        String fecha = (String) tablaPrestamos.getValueAt(fila, 2).toString();
//        regresoDeLibro rg = new regresoDeLibro(codigo, carnet, fecha);

    }//GEN-LAST:event_tablaPrestamosMouseClicked

    private void tablaPrestamosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaPrestamosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaPrestamosKeyPressed

    private void busquedaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaComboBoxActionPerformed

       filtoItemPres();
    }//GEN-LAST:event_busquedaComboBoxActionPerformed


    public void ventanaNuevoEst() {
        NuevoEstudiante ne = new NuevoEstudiante(false, null, tablaStudents);
        ne.setVisible(true);
        ne.setResizable(false);
        ne.setLocationRelativeTo(null);
    }

    public void ventanaNuevoLibro() {
        NuevoLibro nuevoLibro = new NuevoLibro(false, null, tablaLibros);
        nuevoLibro.setVisible(true);
        nuevoLibro.setResizable(false);
        nuevoLibro.setLocationRelativeTo(null);
    }

    public void ventanaNuevoPestamo() {
        NuevoPrestamo nuevoP = new NuevoPrestamo(tablaPrestamos, tablaLibros);
        nuevoP.IniciarFecha();
        nuevoP.setVisible(true);
        nuevoP.setResizable(false);
        nuevoP.setLocationRelativeTo(null);
    }

    public void libroRegresado() {
        regresoDeLibro regreso = new regresoDeLibro(tablaPrestamos, tablaLibros);
        
        int filaSeleccionada = tablaPrestamos.getSelectedRow();
        if (filaSeleccionada != -1) {
            String codigo = tablaPrestamos.getValueAt(filaSeleccionada, 0).toString();
            String carnet = tablaPrestamos.getValueAt(filaSeleccionada, 1).toString();
            String fecha = tablaPrestamos.getValueAt(filaSeleccionada, 2).toString();
            regreso.llenado(codigo, carnet, fecha);
            regreso.diasEfectivos();
            regreso.setVisible(true);
            regreso.setResizable(false);
            regreso.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void filtroPrestamo(int numeroFiltro, String busqueda, int validacion) {
        DefaultTableModel modelo = (DefaultTableModel) tablaPrestamos.getModel();
        
        if (validacion == 0) {
            TableRowSorter<DefaultTableModel> tablaFiltrada = new TableRowSorter<>(modelo);
            tablaPrestamos.setRowSorter(tablaFiltrada);
            tablaFiltrada.setRowFilter(RowFilter.regexFilter(busqueda, numeroFiltro));
            tablaPrestamos.repaint();
        } else if (validacion == -1) {
            tablaPrestamos.setRowSorter(null); // Elimina cualquier filtro aplicado
            tablaPrestamos.setModel(modelo); // Restaura el modelo original de la tabla
            tablaPrestamos.repaint();
        }
    }

   public void filtoItemPres() {
    int validacion = -1;
    int numeroFiltro = -1;
    String busqueda = jTextField3.getText();
    // Obtener el número de filtro según la opción seleccionada en el ComboBox
    String seleccion = busquedaComboBox.getSelectedItem().toString();
    switch (seleccion) {
        case "Todos Los Registros":
            validacion = -1;
            break;
        case "Codigo del Libro":
            validacion = 0;
            numeroFiltro = 0;
            break;
        case "Carnet":
            validacion = 0;
            numeroFiltro = 1;
            break;
        case "Fecha":
            validacion = 0;
            numeroFiltro = 2;
            break;
        default:
            System.out.println("Opción no válida");
            break;
    }

    // Aplicar el filtro
    filtroPrestamo(numeroFiltro, busqueda, validacion);
}
    public void actualizarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaPrestamos.getModel();
        tablaPrestamos.setModel(modelo); 
        tablaPrestamos.setRowSorter(null); 
        
    }

    public JTable getTablaPrestamos() {
        return tablaPrestamos;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activos;
    private javax.swing.JComboBox<String> busquedaComboBox;
    private javax.swing.JButton editarEstudianteBt;
    private javax.swing.JButton editarLibro;
    private javax.swing.JButton eliminarEstudianteBt;
    private javax.swing.JButton eliminarLibro;
    private javax.swing.JButton eliminarPrestamosBt;
    private javax.swing.JButton historial;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelBusqueda;
    private javax.swing.JLabel labelBusquedaLibro;
    private javax.swing.JLabel labelBusquedaPestamo;
    private javax.swing.JButton nuevoEstudiante;
    private javax.swing.JButton nuevoLibroButton;
    private javax.swing.JButton nuevoPrestamosBt;
    private javax.swing.JTable tablaLibros;
    private javax.swing.JTable tablaPrestamos;
    private javax.swing.JTable tablaStudents;
    private javax.swing.JTextPane textPaneCarnet;
    // End of variables declaration//GEN-END:variables
}
